export const TIMING = {
  ZOOM_TRANSITION_DURATION: 350,
  SLIDE_TRANSITION_DURATION: 400,
  ARROW_SLIDE_IN_DURATION: 100,

  INTRO_START_DELAY: 500,
  INTRO_RIPPLE_STEP_DELAY: 100,
  INTRO_RIPPLE_FADE_IN: 500,
  INTRO_RIPPLE_HOLD: 333,
  INTRO_RIPPLE_FADE_OUT: 833,
  INTRO_END_DELAY: 833,
  INTRO_FADE_OUT: 333,

  CLOCK_TITLE_HOLD_DURATION: 1500,
  CLOCK_TITLE_SWAP_DURATION: 200,
} as const;
